---
- name: Lighthouse | Install dependencies
  ansible.builtin.dnf:
    name: git
    state: present
- name: Lighthouse | Copy from git
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    version: master
    dest: /home/user/lighthouse
- name: Lighthouse | Create lighthouse config
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/ligthouse.conf
    mode: "0644"
  notify: Reload nginx
